server {
    listen $PORT;
    root /usr/share/nginx/html;
    index index.html;

    rewrite ^/lemon$ /v4-lemon-grove.html last;
    rewrite ^/minimal$ /v3-mediterranean-minimal.html last;
    rewrite ^/dark$ /v5-dark-cinematic.html last;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }
}
